title: Muhammad Haris Rais,Ph.D. # your name (or website title) here
logo: "/images/picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Assistant Professor
  <br>
  <a href="https://www.vsu.edu/cet/departments/computer-science/"> Computer Science Department</a>
  <br>
  <a href="https://www.vsu.edu"> Virginia State University</a>
  <br><br>
  <a href="https://www.linkedin.com/in/haris-rais/">View My LinkedIn Profile</a> 
  <br><br><br>
  Complete Resume <a href="https://github.com/harisrais/portfolio/master/pdf/CV-HarisRais.pdf">here </a>
  
theme: jekyll-theme-minimal
